# Generated by Django 5.0.2 on 2024-02-15 01:02

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('fiscal_term', models.CharField(max_length=50)),
                ('details', models.TextField(default=' ')),
            ],
            options={
                'db_table': 'master_ledger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default=' ')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('notes', models.TextField(default='Blank')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=' ')),
                ('value', models.CharField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.FloatField(default=0.0)),
                ('details', models.TextField(default='Blank')),
                ('transaction_type',
                 models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=6)),
                ('account', models.CharField(max_length=50)),
                ('notes', models.TextField(default='Blank')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.fiscalterm')),
                ('budget',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_budget_transactions',
                                   to='apps_core.transactioncategory')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='cash_purpose_transactions',
                                              to='apps_core.transactioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0.0)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.fiscalterm')),
                ('category_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.transactioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='BankLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.FloatField(default=0.0)),
                ('details', models.TextField(default='Blank')),
                ('transaction_type',
                 models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=6)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0)),
                ('notes', models.TextField(default='Blank')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.fiscalterm')),
                ('budget',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_budget_transactions',
                                   to='apps_core.transactioncategory')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='bank_purpose_transactions',
                                              to='apps_core.transactioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='VenmoLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('type', models.CharField(default='Payment', max_length=50)),
                ('status', models.CharField(default='Complete', max_length=50)),
                ('note', models.TextField(default='Blank')),
                ('from_user', models.CharField(default='Blank', max_length=50)),
                ('to_user', models.CharField(default='Blank', max_length=50)),
                ('total_amount', models.FloatField(default=0.0)),
                ('tip_amount', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('fee_amount', models.FloatField(default=0.0)),
                ('net_amount', models.FloatField(default=0.0)),
                ('tax_rate', models.FloatField(default=0.0)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('funding_source', models.CharField(default='Blank', max_length=50)),
                ('funding_destination', models.CharField(default='Blank', max_length=50)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0)),
                ('transaction_type',
                 models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=6)),
                ('budget',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_venmo_ledgers',
                                   to='apps_core.transactioncategory')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.fiscalterm')),
                ('purpose',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_venmo_ledgers',
                                   to='apps_core.transactioncategory')),
            ],
        ),
    ]
