# Generated by Django 5.0.2 on 2024-02-15 01:02

import django_db_views.migration_functions
import django_db_views.operations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0001_initial'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                "WITH cashledger_cte AS (\n        SELECT \n            transaction_id, \n            date, \n            amount, \n            transaction_type, \n            account, \n            budget_id, \n            purpose_id, \n            fiscal_id, \n            details \n        FROM \n            apps_core_cashledger\n        ), \n        bankledger_cte AS (\n        SELECT \n            transaction_id, \n            date, \n            amount, \n            transaction_type, \n            'wells' AS account, \n            budget_id, \n            purpose_id, \n            fiscal_id, \n            details \n        FROM \n            apps_core_bankledger\n        ), \n        venmoledger_cte AS (\n        SELECT \n            transaction_id, \n            date, \n            net_amount AS amount, \n            transaction_type, \n            'venmo' AS account, \n            budget_id, \n            purpose_id, \n            fiscal_id, \n            note AS details \n        FROM \n            apps_core_venmoledger\n        ), \n        combined_ledger_cte as (\n        SELECT \n            * \n        FROM \n            cashledger_cte \n        UNION \n        SELECT \n            * \n        FROM \n            bankledger_cte \n        UNION \n        SELECT \n            * \n        FROM \n            venmoledger_cte\n        ), \n        populate_budget_cte as (\n        Select \n            transaction_id, \n            date, \n            amount, \n            transaction_type, \n            account, \n            value as budget, \n            purpose_id, \n            fiscal_id, \n            details \n        from \n            combined_ledger_cte \n            left join apps_core_transactioncategory on budget_id = id\n        ), \n        populate_purpose_cte as (\n        Select \n            transaction_id, \n            date, \n            amount, \n            transaction_type, \n            account, \n            budget, \n            value as purpose, \n            fiscal_id, \n            details \n        from \n            populate_budget_cte \n            left join apps_core_transactioncategory on purpose_id = id\n        ), \n        populate_fiscal_term_cte as (\n        Select \n            transaction_id, \n            date, \n            amount, \n            transaction_type, \n            account, \n            budget, \n            purpose, \n            semester as fiscal_term, \n            details \n        from \n            populate_purpose_cte \n            left join apps_core_fiscalterm on fiscal_id = id\n        ) \n        select \n        row_number() over () as id, \n        * \n        from \n        populate_fiscal_term_cte",
                'master_ledger', engine='django.db.backends.postgresql'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'master_ledger',
                                                                                   engine='django.db.backends.postgresql'),
            atomic=False,
        ),
    ]
