# Generated by Django 5.0.2 on 2024-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
