# Generated by Django 5.0.2 on 2024-02-09 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0002_ledger_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger',
            new_name='MasterLedger',
        ),
    ]
