# Generated by Django 5.0.2 on 2024-02-09 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0003_rename_ledger_masterledger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterledger',
            old_name='name',
            new_name='details',
        ),
        migrations.AddField(
            model_name='masterledger',
            name='account',
            field=models.TextField(default='Cash'),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='budget',
            field=models.TextField(default='Dues'),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='purpose',
            field=models.TextField(default='Dues'),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='transaction_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='masterledger',
            name='transaction_type',
            field=models.TextField(default='credit'),
        ),
    ]
