# Generated by Django 5.0.2 on 2024-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0004_rename_name_masterledger_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterledger',
            name='account',
            field=models.TextField(default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='budget',
            field=models.TextField(default='Dues', max_length=100),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='details',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='masterledger',
            name='purpose',
            field=models.TextField(default='Dues', max_length=100),
        ),
    ]
