# Generated by Django 5.0.2 on 2024-02-16 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0004_bankledger_batch_id_cashledger_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankledger',
            table='bank_ledger',
        ),
        migrations.AlterModelTable(
            name='budget',
            table='budget',
        ),
        migrations.AlterModelTable(
            name='cashledger',
            table='cash_ledger',
        ),
        migrations.AlterModelTable(
            name='fiscalterm',
            table='fiscal_term',
        ),
        migrations.AlterModelTable(
            name='transactioncategory',
            table='transaction_category',
        ),
        migrations.AlterModelTable(
            name='venmoledger',
            table='venmo_ledger',
        ),
    ]
