# Generated by Django 5.0.2 on 2024-02-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0005_alter_masterledger_account_alter_masterledger_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterledger',
            name='details',
            field=models.TextField(default='None', max_length=300),
        ),
    ]
