# Generated by Django 5.0.2 on 2024-02-19 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apps_core', '0006_auto_20240216_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='category_id',
            new_name='category',
        ),
    ]
